### ISSUE TITLE
Update hostname fails without dbus

### ISSUE THREAD

**Issue by jkirk** [Oefenweb/ansible-hostname#12]
We use the `Oefenweb.hostname` role to set up the hostname on our template VMs. These template VMs are minimal Debian/stretch installations (made via [debootstrap](https://manpages.debian.org/stretch/debootstrap/debootstrap.8.en.html) / [grml-debootstrap](https://github.com/grml/grml-debootstrap)) to allow full flexibility. We bootstrap the template VMs mainly with [robertdebock.bootstrap](https://github.com/robertdebock/ansible-role-bootstrap) and your `Oefenweb.hostname` roles. (Have a look [here](https://github.com/jkirk/ansible-site-template/blob/master/bootstrap-template.yml) if you like).

But when applying the `hostname` role, the playbook fails:

```
TASK [Oefenweb.hostname : update the hostname - hostname module] 
fatal: [template-debian-stretch.in.example.com]: FAILED! => {"changed": false, "msg": "Command failed rc=1, out=, err=Failed to create bus connection: No such file or directory\n"}
        to retry, use: --limit @/home/jkirk/projects/ansible/bootstrap-template.retry
```

After manually installing `dbus` the role works just fine. I think `Oefenweb.hostname` should make sure that `dbus` is installed.

**Comment by tersmitten** [comment]
Can you make a PR and verify that it works for all supported operating systems? See the `Vagrantfile`. Thanks in advance.

**Comment by EvanCarroll** [comment]
I habe dbus installed, i still get this error.

**Comment by jkirk** [comment]
I just compared the package list of the Vagrant `bento/debian-10` box with my (basic grml-debootstrap) installation and noticed that it contains 99 more packages, including `dbus`:

```
% wc -l dpkg.vagrant.list
399 dpkg.vagrant.list
% wc -l dpkg.bootstrap.list
300 dpkg.bootstrap.list
% grep dbus dpkg.vagrant.list  
ii  dbus                           1.12.20-0+deb10u1                   amd64        simple interprocess messaging system (daemon and utilities)
ii  libdbus-1-3:amd64              1.12.20-0+deb10u1                   amd64        simple interprocess messaging system (library)
% grep dbus dpkg.bootstrap.list
```

As @EvanCarroll  also encountered the problem `dbus` is most probably not the only package needed. @EvanCarroll could you please try to compare the package list of you installation with the corresponding Vagrant box. We then might find the other missing package(s). For now I am pretty sure, `dbus` is mandatory for this role and should be added.

I will try to prepare a PR and verify it for all supported operating systems.
