### ISSUE TITLE
Missing parameter zone identifier for IPv6 hosts

### ISSUE THREAD

**Issue by Migsi** [Oefenweb/ansible-hostname#19]
I'm using this role since quite a while and am very happy with it. Though, when recently switching our container network to IPv6 only, I discovered, that there is currently no possibility to add an zone specifier to additional_hosts. [This is a requirement when working with link local IPv6 addresses](https://labs.ripe.net/author/philip_homburg/whats-the-deal-with-ipv6-link-local-addresses/), due to the possibility of using the same address ranges on multiple interfaces (this problem kinda exists for IPv4 too, but apparently it does not require identifiers somehow).

My current workaround is appending the zone identifier to the address itself.

UPDATE:
I researched a bit and found that [/etc/hosts actually does not (yet) support zone identifiers](https://unix.stackexchange.com/questions/174767/ipv6-scope-id-in-etc-hosts). Hosts with such identifiers are not parsed properly and skipped, thus they won't be available. As this issue seems to beeing worked on, I'd suggest adding a config option anyway, but mentioning that currently there is limited support for its usage only.

**Comment by tersmitten** [comment]
Due to inactivity
