### ISSUE TITLE
v2.0.24 is not available in ansible galaxy

### ISSUE THREAD

**Issue by sakoula** [Oefenweb/ansible-hostname#22]
thanks for your really great work!!!!

**Comment by tersmitten** [comment]
Sure?

https://galaxy.ansible.com/ui/standalone/roles/Oefenweb/hostname/versions/

**Comment by sakoula** [comment]
released 5 hours ago?

<img width="1127" alt="image" src="https://github.com/user-attachments/assets/f75164b3-1d9d-4422-9ecc-9247ce3167c8">

Thanks!

**Comment by sakoula** [comment]
btw do you want me to report if I find any role differences in versions etc between github and galaxy in the future?

Thanks!

**Comment by tersmitten** [comment]
Yes, please

**Comment by tersmitten** [comment]
I manually kicked the import, this might have fixed the problem.

**Comment by sakoula** [comment]
thanks!
