### ISSUE TITLE
Suggestion for renaming variables

### ISSUE THREAD

**Issue by mvdriel** [Oefenweb/ansible-hostname#6]
It is probably more convenient to rename the following variables:
 - hostname_short ==> hostname
 - short_name ==> hostname
 - hostname ==> fqdn

@tersmitten If you agree, I will create a pull request for it. :)

**Comment by tersmitten** [comment]
I understand your idea, but I rather not change the names because in the inventory the're also named that way:

* `inventory_hostname`
* `inventory_hostname_short`

@mvdriel Do you agree?

**Comment by mvdriel** [comment]
@tersmitten Good point, it is probably better to keep it that way. But using the same name for the "short hostname" is still a good idea; i.e. renaming short_name to hostname_short. What do you think?

**Comment by tersmitten** [comment]
@mvdriel: I can't find `short_name` in the role

**Comment by mvdriel** [comment]
@tersmitten Sorry, my wrong.
